name: Run unit tests

on: [push, pull_request]

jobs:
  build-and-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Debug
        run: ls

      - name: Navigate to tests
        run: cd tests

      - name: Debug
        run: ls
 
      - name: Create Build
        run: make
      
      - name: Run tests
        run: ./tests
      
      - name: Cleanup
        run: make clean