name: Run unit tests

on: [push, pull_request]

jobs:
  build-and-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup and run tests
        working-directory: ./tests
        run: |
          make
          ./tests
          make clean